add any_dirty output

diff --git a/.github/workflows/test-action.yaml b/.github/workflows/test-action.yaml
--- a/.github/workflows/test-action.yaml
+++ b/.github/workflows/test-action.yaml
@@ -68,11 +68,17 @@ jobs:
       - name: Validate output
         run: |
           expected="gta.test/foo gta.test/fooclient gta.test/fooclientclient"
-          actual="${{ steps.gta.outputs.changed_packages }}"
+          actual="${{ steps.gta.outputs.dirty_packages }}"
           if [ "$actual" != "$expected" ]; then
             echo "Error: Changed packages do not match expected."
             echo "Expected: $expected"
             echo "Actual: $actual"
             exit 1
           fi
-          echo "Validation successful: $actual"
+
+          if [ "${{ steps.gta.outputs.any_dirty }}" != "true" ]; then
+            echo "Error: any_dirty should be true"
+            exit 1
+          fi
+
+          echo "Validation successful"
